//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_ASPNET_Clase2LAB4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class base1Entities : DbContext
    {
        public base1Entities()
            : base("name=base1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Departamentos> Departamentos { get; set; }
        public DbSet<EmpleadoDepartamento> EmpleadoDepartamento { get; set; }
        public DbSet<Empleados> Empleados { get; set; }
    }
}
